#' ---
#' title: VBD surveys 
#' subtitle: Labels in german (official), french or english (AI translation)
#' author: jriou
#' date: 2025-06-10
#' ---


#extraction of the value of municipalities
list_municipalities = read_excel("data/Gemeindestand.xlsx")
list_municipalities=list_municipalities %>% filter(Kanton=="BE")
value_commune=list_municipalities$`BFS Gde-nummer`
names(value_commune)=list_municipalities$Gemeindename



br_002_labels = function(dat_in, lang){
  
  if(lang == "FR") {
    Sys.setlocale("LC_ALL", "fr_FR.UTF-8")
    dat0 = dat_in %>%
      # étiquettes des variables
      labelled::set_variable_labels(
        record_id="Identifiant",
        redcap_event_name="Time point",
        yob="Année de naissance",
        age_incl="Âge à l'inclusion",
        bl_sex="Quel sexe vous a été attribué à la naissance?",
        bl_gender_def="Laquelle des désignations suivantes correspond le mieux à votre sexe social, vécu et ressenti (genre)?",
        bl_commune = "Dans quelle municipalité habitez-vous?",
        bl_live_ch_since = "Depuis quand vivez-vous en Suisse?",
        bl_education = "Quel est votre formation achevée la plus élevée?",
        bl_scg_marital_status = "Quelle est votre situation familiale?",
        bl_vacc_yn = "Avez-vous déjà reçu des vaccins?",
        bl_ppre_challenge = "Si vous pensez à la prochaine pandémie, quels sont, selon vous, les principaux défis à relever en matière de préparation?",
        bl_ppre_challenge___1 = "Maintien de la sensibilisation de la population à la possibilité d'une pandémie",
        bl_ppre_challenge___2 = "Maintien de l'engagement du gouvernement envers la préparation en vue d'une pandémie",
        bl_ppre_challenge___3 = "Atténuation des effets du changement climatique",
        bl_ppre_challenge___4 = "Obstacles réglementaires au renforcement des capacités de production de vaccins dans les pays à revenu faible ou intermédiaire",
        bl_ppre_challenge___5 = "Renforcement des capacités de surveillance pour identifier les nouveaux agents pathogènes pandémiques potentiels",
        bl_ppre_challenge___6 = "Lutte contre la désinformation concernant les menaces de pandémie",
        bl_ppre_challenge___7 = "Installation d'une ventilation adéquate sur les lieux de travail et dans les habitations",
        eq5d5l_vas2_swi_ger = "Nous aimerions savoir dans quelle mesure votre santé est bonne ou mauvaise AUJOURD'HUI. Cette échelle est numérotée de 0 à 100. 100 correspond à la meilleure santé que vous puissiez imaginer. 0 correspond à la pire santé que vous puissiez imaginer.
                              Veuillez cliquer sur l'échelle afin d'indiquer votre état de santé AUJOURD'HUI.",
        eq5d_mb_5l_swi_ger = "Veuillez cliquer sur UNE case, celle qui décrit le mieux votre santé AUJOURD'HUI. Mobilité",
        bl_abroad_yn = "Avez-vous déjà séjourné plus de deux jours à l'étranger?",
        bl_continent = "Sur quel continent?",
        bl_continent___1 = "Europe",
        bl_continent___2 = "Amérique du Nord",
        bl_continent___3 = "Amérique Centrale",
        bl_continent___4 = "Amérique du Sud",
        bl_continent___5 = "Afrique",
        bl_continent___6 = "Asie",
        bl_continent___7 = "Océanie",
        bl_vbd_tick_yn = "La classeriez-vous dans la catégorie des maladies à transmission vectorielle?",
        bl_vbd_diseases = "Avez-vous déjà entendu parler des maladies suivantes?",
        bl_vbd_diseases___1 = "Fièvre du Nil occidental",
        bl_vbd_diseases___2 = "Dengue",
        bl_vbd_diseases___3 = "Zika",
        bl_vbd_diseases___4 = "Chikungunya",
        bl_vbd_diseases___5 = "Maladie de Lyme",
        bl_vbd_diseases___6 = "Grippe",
        bl_vbd_diseases___7 = "Rougeole",
        bl_vbd_diseases___0 = "Aucune de ces réponses",
        bl_vbd_vector_dis = "Parmi la liste de maladies suivante, lesquelles sont, selon vous, des maladies à transmission vectorielle?",
        bl_vbd_vector_dis___1 = "Fièvre du Nil occidental",
        bl_vbd_vector_dis___2 = "Dengue",
        bl_vbd_vector_dis___3 = "Zika",
        bl_vbd_vector_dis___4 = "Chikungunya",
        bl_vbd_vector_dis___5 = "Maladie de Lyme",
        bl_vbd_vector_dis___6 = "Grippe",
        bl_vbd_vector_dis___7 = "Rougeole",
        bl_vbd_vector_dis___0 = "Aucune de ces réponses",
        bl_vbd_organism = "Avez-vous déjà entendu parler des organismes suivants?",
        bl_vbd_organism___1 = "Tiques",
        bl_vbd_organism___2 = "Moustiques",
        bl_vbd_organism___3 = "Guêpes",
        bl_vbd_organism___4 = "Punaises de lit",
        bl_vbd_organism___0 = "Aucune de ces réponses",
        bl_vbd_transmitter = "Parmi les organismes suivants, lesquels sont des vecteurs de transmission de maladies à l'homme?",
        bl_vbd_transmitter___1 = "Tiques",
        bl_vbd_transmitter___2 = "Moustiques",
        bl_vbd_transmitter___3 = "Guêpes",
        bl_vbd_transmitter___4 = "Punaises de lit",
        bl_vbd_transmitter___0 = "Aucune de ces réponses",
        bl_vbd = "Pouvez-vous relier la maladie et son vecteur correspondant? Identifiez le vecteur qui transmet chacune des maladies présentées à gauche en sélectionnant un vecteur par ligne. Par exemple, 'l'encéphalite à tiques' est transmise par les 'tiques'.",
        bl_vbd_tick_enc = "Vecteur de l'encéphalite à tiques",
        bl_vbd_wnf = "Vecteur de la fièvre du Nil occidental",
        bl_vbd_dengue = "Vecteur de la dengue",
        bl_vbd_zika = "Vecteur du Zika ",
        bl_vbd_chikun = "Vecteur du Chikungunya",
        bl_vbd_lyme = "Vecteur de la maladie de Lyme",
        bl_vbd_influenza = "Vecteur de la grippe",
        bl_vbd_measle = "Vecteur de la rougeole",
        bl_vbd_tickbite_nr = "Combien de piqûres de tiques subissez-vous en moyenne chaque année, du printemps à l'automne?",
        bl_vbd_mosqbite_nr = "En été, à quelle fréquence êtes-vous piqué(e) par des moustiques?",
        bl_vbd_meas_tick = "Quelles mesures avez-vous prises au cours des 12 derniers mois pour vous protéger, vous et votre famille, contre les piqûres de tiques ou les maladies transmises par les tiques?",
        bl_vbd_meas_tick___1 = "Rechercher et enlever les tiques après avoir été en plein air",
        bl_vbd_meas_tick___2 = "Porter des vêtements couvrants",
        bl_vbd_meas_tick___3 = "Utiliser un répulsif insectes sur la peau les vêtements",
        bl_vbd_meas_tick___4 = "Éviter les espaces pendant la période d'activité des tiques",
        bl_vbd_meas_tick___88 = "Autre mesure: {bl_vbd_oth_meas}",
        bl_vbd_meas_tick___0 = "Aucune mesure de prévention active",
        bl_vbd_meas_mosq = "Quelles mesures avez-vous prises au cours des 12 derniers mois pour vous protéger, vous et votre famille, contre les piqûres de moustique?",
        bl_vbd_meas_mosq___1 = "Utiliser un répulsif",
        bl_vbd_meas_mosq___2 = "Porter des vêtements couvrants",
        bl_vbd_meas_mosq___3 = "Brûler des bobines antimoustiques",
        bl_vbd_meas_mosq___4 = "Séjour dans des clos",
        bl_vbd_meas_mosq___5 = "Installer des moustiquaires aux fenêtres",
        bl_vbd_meas_mosq___6 = "Faire tourner des ventilateurs",
        bl_vbd_meas_mosq___7 = "Installer un spray insectifuge automatique",
        bl_vbd_meas_mosq___8 = "Installer des moustiquaires",
        bl_vbd_meas_mosq___9 = "Éliminer les récipients avec de l'eau stagnante",
        bl_vbd_meas_mosq___88 = "Autre mesure: {bl_vbd_oth_meas_0}",
        bl_vbd_meas_mosq___0 = "Aucune mesure prévention active",
        bl_vbd_meas_tick_eff = "Laquelle des mesures suivantes vous semble efficace pour protéger la population contre les maladies transmises par les tiques?",
        bl_vbd_meas_tick_eff___1 = "Appliquer des pesticides dans l'environnement",
        bl_vbd_meas_tick_eff___2 = "Utiliser des méthodes de contrôle biologique dans l'environnement (p. ex. prédateurs dans le cas des vecteurs)",
        bl_vbd_meas_tick_eff___3 = "Éliminer la végétation dans les zones boisées",
        bl_vbd_meas_tick_eff___4 = "Protéger les cerfs contre les tiques",
        bl_vbd_meas_tick_eff___5 = "Contrôler le nombre de cerfs dans les zones boisées accessibles au public",
        bl_vbd_meas_tick_eff___6 = "Empêcher les cerfs de fréquenter les zones boisées accessibles au public au moyen de barrières",
        bl_vbd_meas_tick_eff___7 = "Protéger les petits rongeurs contre les tiques",
        bl_vbd_meas_tick_eff___8 = "Promouvoir l'utilisation de mesures de protection individuelle",
        bl_vbd_meas_tick_eff___0 = "Aucune de ces réponses",
        bl_vbd_meas_mosq_eff = "Laquelle des mesures suivantes vous semble efficace pour protéger la population contre les maladies transmises par les moustiques?",
        bl_vbd_meas_mosq_eff___1 = "Appliquer des pesticides dans l'environnement",
        bl_vbd_meas_mosq_eff___2 = "Utiliser des méthodes de contrôle biologique (p. ex. prédateurs dans le cas des vecteurs)",
        bl_vbd_meas_mosq_eff___3 = "Éliminer l'eau stagnante dans les conteneurs",
        bl_vbd_meas_mosq_eff___4 = "Appliquer des larvicides dans l'environnement",
        bl_vbd_meas_mosq_eff___5 = "Installer un pulvérisateur de répulsif",
        bl_vbd_meas_mosq_eff___6 = "Installer un piège à moustiques",
        bl_vbd_meas_mosq_eff___7 = "Libérer des moustiques irradiés ou génétiquement modifiés",
        bl_vbd_meas_mosq_eff___8 = "Promouvoir l'utilisation de mesures de protection individuelle",
        bl_vbd_meas_mosq_eff___0 = "Aucune de ces réponses",
        bl_vbd_dis_problem = "Considérez-vous que les maladies suivantes constituent actuellement un problème de santé pour les personnes vivant en Suisse?",
        bl_vbd_dis_problem___1 = "Encéphalite à tiques",
        bl_vbd_dis_problem___2 = "Fièvre du Nil occidental",
        bl_vbd_dis_problem___3 = "Dengue",
        bl_vbd_dis_problem___4 = "Zika",
        bl_vbd_dis_problem___5 = "Chikungunya",
        bl_vbd_dis_problem___6 = "Maladie de Lyme",
        bl_vbd_meth_yn = "Pensez-vous que des mesures de contrôle des vecteurs soient nécessaires en Suisse?",
        isco_lvl1 = "Domaine d'activité selon la nomenclature CH-ISCO 2019"
      ) %>%
      # étiquettes de valeurs
      labelled::set_value_labels(
        record_id="Identifiant",
        redcap_event_name="Time point",
        yob="Année de naissance",
        age_incl="Âge à l'inclusion",
        bl_sex=c("Féminin"=2,"Masculin"=1,"Intersexe"=3),
        bl_gender_def=c(
          "Féminin" = 2,
          "Masculin" = 1,
          "Autre, merci de préciser..." = 3
        ),
        bl_commune = value_commune,
        bl_live_ch_since = c(
          "Depuis la naissance" = 1,
          "Né/e en Suisse mais ai aussi vécu à l'étranger" = 2,
          "Né/e à l’étranger" = 3
        ),
        bl_education = c(
          "Aucune" = 0,
          "Ecole obligatoire inachevée" = 1,
          "Ecole obligatoire" = 2,
          "Formation d'un an / offre de transition" = 3,
          "Ecole de culture générale / école de degré diplôme" = 4,
          "Apprentissage en entreprise (CFC, AFP) / formation professionnelle élémentaire / école professionnelle / école de commerce" = 5,
          "Maturité gymnasiale / brevet d’enseignement" = 6,
          "Maturité professionnelle / spécialisée" = 7,
          "Examen professionnel avec brevet fédéral / examen professionnel supérieur avec diplôme fédéral/maîtrise" = 8,
          "Ecole professionnelle supérieure (ES)" = 9,
          "Bachelor: université, EPF, haute école spécialisée, haute école pédagogique (y compris diplôme HES/HEP)" = 10,
          "Master: université, EPF, haute école spécialisée, haute école pédagogique (y compris licence/diplôme université / EPF)" = 11,
          "Doctorat / habilitation" = 12
        ),
        bl_scg_marital_status = c(
          "Marié(e), vie commune avec le/la conjoint(e)" = 1,
          "Marié(e), durablement séparé(e)" = 2,
          "Partenariat enregistré entre personnes de même sexe, vie commune" = 3,
          "Partenariat enregistré entre personnes de même sexe, séparé(e)" = 4,
          "Célibataire, partenariat stable" = 5,
          "Célibataire, vie seul(e)" = 6,
          "Divorcé(e), partenariat abrogé" = 7,
          "Veuf/veuve, partenaire décédé(e)" = 8
        ),
        bl_vacc_yn = c("Oui"=1, "Non"=1),
        bl_ppre_challenge___1 = c("Oui"=1, "Non"=1),
        bl_ppre_challenge___2 = c("Oui"=1, "Non"=1),
        bl_ppre_challenge___3 = c("Oui"=1, "Non"=1),
        bl_ppre_challenge___4 = c("Oui"=1, "Non"=1),
        bl_ppre_challenge___5 = c("Oui"=1, "Non"=1),
        bl_ppre_challenge___6 = c("Oui"=1, "Non"=1),
        bl_ppre_challenge___7 = c("Oui"=1, "Non"=1),
        eq5d5l_vas2_swi_ger = ,
        eq5d_mb_5l_swi_ger = ,
        bl_abroad_yn = ,
        bl_continent___1 = c("Oui"=1, "Non"=1),
        bl_continent___2 = c("Oui"=1, "Non"=1),
        bl_continent___3 = c("Oui"=1, "Non"=1),
        bl_continent___4 = c("Oui"=1, "Non"=1),
        bl_continent___5 = c("Oui"=1, "Non"=1),
        bl_continent___6 = c("Oui"=1, "Non"=1),
        bl_continent___7 = c("Oui"=1, "Non"=1),
        bl_vbd_tick_yn = ,
        bl_vbd_diseases___1 = c("Oui"=1, "Non"=1),
        bl_vbd_diseases___2 = c("Oui"=1, "Non"=1),
        bl_vbd_diseases___3 = c("Oui"=1, "Non"=1),
        bl_vbd_diseases___4 = c("Oui"=1, "Non"=1),
        bl_vbd_diseases___5 = c("Oui"=1, "Non"=1),
        bl_vbd_diseases___6 = c("Oui"=1, "Non"=1),
        bl_vbd_diseases___7 = c("Oui"=1, "Non"=1),
        bl_vbd_diseases___0 = c("Oui"=1, "Non"=1),
        bl_vbd_vector_dis___1 = c("Oui"=1, "Non"=1),
        bl_vbd_vector_dis___2 = c("Oui"=1, "Non"=1),
        bl_vbd_vector_dis___3 = c("Oui"=1, "Non"=1),
        bl_vbd_vector_dis___4 = c("Oui"=1, "Non"=1),
        bl_vbd_vector_dis___5 = c("Oui"=1, "Non"=1),
        bl_vbd_vector_dis___6 = c("Oui"=1, "Non"=1),
        bl_vbd_vector_dis___7 = c("Oui"=1, "Non"=1),
        bl_vbd_vector_dis___0 = c("Oui"=1, "Non"=1),
        bl_vbd_organism___1 = c("Oui"=1, "Non"=1),
        bl_vbd_organism___2 = c("Oui"=1, "Non"=1),
        bl_vbd_organism___3 = c("Oui"=1, "Non"=1),
        bl_vbd_organism___4 = c("Oui"=1, "Non"=1),
        bl_vbd_organism___0 = c("Oui"=1, "Non"=1),
        bl_vbd_transmitter___1 = c("Oui"=1, "Non"=1),
        bl_vbd_transmitter___2 = c("Oui"=1, "Non"=1),
        bl_vbd_transmitter___3 = c("Oui"=1, "Non"=1),
        bl_vbd_transmitter___4 = c("Oui"=1, "Non"=1),
        bl_vbd_transmitter___0 = c("Oui"=1, "Non"=1),
        bl_vbd_tick_enc = c(
          "Moustiques" = 1,
          "Tiques" = 2,
          "Guêpes" = 3,
          "Punaises de lit" = 4,
          "Aucune de ces réponses" = 0,
          "Je ne sais pas" = 99
        ),
        bl_vbd_wnf = c(
          "Moustiques" = 1,
          "Tiques" = 2,
          "Guêpes" = 3,
          "Punaises de lit" = 4,
          "Aucune de ces réponses" = 0,
          "Je ne sais pas" = 99
        ),
        bl_vbd_dengue = c(
          "Moustiques" = 1,
          "Tiques" = 2,
          "Guêpes" = 3,
          "Punaises de lit" = 4,
          "Aucune de ces réponses" = 0,
          "Je ne sais pas" = 99
        ),
        bl_vbd_zika = c(
          "Moustiques" = 1,
          "Tiques" = 2,
          "Guêpes" = 3,
          "Punaises de lit" = 4,
          "Aucune de ces réponses" = 0,
          "Je ne sais pas" = 99
        ),
        bl_vbd_chikun = c(
          "Moustiques" = 1,
          "Tiques" = 2,
          "Guêpes" = 3,
          "Punaises de lit" = 4,
          "Aucune de ces réponses" = 0,
          "Je ne sais pas" = 99
        ),
        bl_vbd_lyme = c(
          "Moustiques" = 1,
          "Tiques" = 2,
          "Guêpes" = 3,
          "Punaises de lit" = 4,
          "Aucune de ces réponses" = 0,
          "Je ne sais pas" = 99
        ),
        bl_vbd_influenza = c(
          "Moustiques" = 1,
          "Tiques" = 2,
          "Guêpes" = 3,
          "Punaises de lit" = 4,
          "Aucune de ces réponses" = 0,
          "Je ne sais pas" = 99
        ),
        bl_vbd_measle = c(
          "Moustiques" = 1,
          "Tiques" = 2,
          "Guêpes" = 3,
          "Punaises de lit" = 4,
          "Aucune de ces réponses" = 0,
          "Je ne sais pas" = 99
        ),
        bl_vbd_tickbite_nr = c("0"=0,"1-3"=1,"4-6"=2,"7-9"=3,"10+"=4),
        bl_vbd_mosqbite_nr = c("Chaque jour"=1,"Au moins une fois par semaine"=2,"Au moins une fois par mois"=3,"Au moins une fois par an"=4,"Moins d'une fois par an"=5,"Jamais"=0,"Je ne sais pas"=99),
        bl_vbd_meas_tick___1 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick___2 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick___3 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick___4 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick___88 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick___0 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___1 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___2 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___3 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___4 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___5 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___6 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___7 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___8 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___9 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___88 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq___0 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___1 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___2 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___3 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___4 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___5 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___6 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___7 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___8 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_tick_eff___0 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___1 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___2 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___3 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___4 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___5 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___6 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___7 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___8 = c("Oui"=1, "Non"=1),
        bl_vbd_meas_mosq_eff___0 = c("Oui"=1, "Non"=1),
        bl_vbd_dis_problem___1 = c("Oui"=1, "Non"=1),
        bl_vbd_dis_problem___2 = c("Oui"=1, "Non"=1),
        bl_vbd_dis_problem___3 = c("Oui"=1, "Non"=1),
        bl_vbd_dis_problem___4 = c("Oui"=1, "Non"=1),
        bl_vbd_dis_problem___5 = c("Oui"=1, "Non"=1),
        bl_vbd_dis_problem___6 = c("Oui"=1, "Non"=1),
        bl_vbd_meth_yn = c("Oui"=1, "Non"=1,"Je ne sais pas"=99)
      ) 
  }
  
  if(lang == "EN") {
    Sys.setlocale("LC_ALL", "en_US.UTF-8")
    dat0 = dat_in %>%
      # variable labels
      labelled::set_variable_labels(
        record_id                  = "Record ID",
        redcap_event_name          = "Time point",
        yob                        = "Year of birth",
        age_incl                   = "Age at inclusion",
        bl_sex                     = "What sex were you assigned at birth?",
        bl_gender_def              = "Which of the following labels best describes your social and felt gender?",
        bl_commune                 = "In which municipality do you live?",
        bl_live_ch_since           = "Since when have you been living in Switzerland?",
        bl_education               = "What is your highest completed education?",
        bl_scg_marital_status      = "What is your marital status?",
        bl_vacc_yn                 = "Have you ever received any vaccines?",
        bl_ppre_challenge          = "Thinking about the next pandemic, what do you see as the main challenges for preparedness?",
        bl_ppre_challenge___1      = "Maintaining public awareness of a possible pandemic",
        bl_ppre_challenge___2      = "Maintaining government commitment to pandemic preparedness",
        bl_ppre_challenge___3      = "Mitigating the effects of climate change",
        bl_ppre_challenge___4      = "Regulatory barriers to scaling up vaccine production in low- and middle-income countries",
        bl_ppre_challenge___5      = "Strengthening surveillance to identify potential pandemic pathogens",
        bl_ppre_challenge___6      = "Combating misinformation about pandemic threats",
        bl_ppre_challenge___7      = "Installing adequate ventilation in workplaces and homes",
        eq5d5l_vas2_swi_ger         = "How good or bad is your health TODAY? This scale runs from 0 (worst health imaginable) to 100 (best health imaginable). Please click on the scale to indicate your health TODAY.",
        eq5d_mb_5l_swi_ger         = "Please click ONE box that best describes your health TODAY: Mobility",
        bl_abroad_yn               = "Have you ever stayed abroad for more than two days?",
        bl_continent               = "On which continent?",
        bl_continent___1           = "Europe",
        bl_continent___2           = "North America",
        bl_continent___3           = "Central America",
        bl_continent___4           = "South America",
        bl_continent___5           = "Africa",
        bl_continent___6           = "Asia",
        bl_continent___7           = "Oceania",
        bl_vbd_tick_yn             = "Would you classify it as a vector-borne disease?",
        bl_vbd_diseases            = "Have you heard of the following diseases?",
        bl_vbd_diseases___1        = "West Nile fever",
        bl_vbd_diseases___2        = "Dengue",
        bl_vbd_diseases___3        = "Zika",
        bl_vbd_diseases___4        = "Chikungunya",
        bl_vbd_diseases___5        = "Lyme disease",
        bl_vbd_diseases___6        = "Influenza",
        bl_vbd_diseases___7        = "Measles",
        bl_vbd_diseases___0        = "None of these",
        bl_vbd_vector_dis          = "Which of these do you think are vector-borne diseases?",
        bl_vbd_vector_dis___1      = "West Nile fever",
        bl_vbd_vector_dis___2      = "Dengue",
        bl_vbd_vector_dis___3      = "Zika",
        bl_vbd_vector_dis___4      = "Chikungunya",
        bl_vbd_vector_dis___5      = "Lyme disease",
        bl_vbd_vector_dis___6      = "Influenza",
        bl_vbd_vector_dis___7      = "Measles",
        bl_vbd_vector_dis___0      = "None of these",
        bl_vbd_organism            = "Have you heard of the following organisms?",
        bl_vbd_organism___1        = "Ticks",
        bl_vbd_organism___2        = "Mosquitoes",
        bl_vbd_organism___3        = "Wasps",
        bl_vbd_organism___4        = "Bed bugs",
        bl_vbd_organism___0        = "None of these",
        bl_vbd_transmitter         = "Which of these organisms transmit diseases to humans?",
        bl_vbd_transmitter___1     = "Ticks",
        bl_vbd_transmitter___2     = "Mosquitoes",
        bl_vbd_transmitter___3     = "Wasps",
        bl_vbd_transmitter___4     = "Bed bugs",
        bl_vbd_transmitter___0     = "None of these",
        bl_vbd                     = "Match each disease on the left with its vector on the right (one per row). E.g. ’tick-borne encephalitis’ → ’ticks’.",
        bl_vbd_tick_enc            = "Vector for tick-borne encephalitis",
        bl_vbd_wnf                 = "Vector for West Nile fever",
        bl_vbd_dengue              = "Vector for dengue",
        bl_vbd_zika                = "Vector for Zika",
        bl_vbd_chikun              = "Vector for chikungunya",
        bl_vbd_lyme                = "Vector for Lyme disease",
        bl_vbd_influenza           = "Vector for influenza",
        bl_vbd_measle              = "Vector for measles",
        bl_vbd_tickbite_nr         = "How many tick bites do you receive on average per year (spring to autumn)?",
        bl_vbd_mosqbite_nr         = "In summer, how often are you bitten by mosquitoes?",
        bl_vbd_meas_tick           = "In the last 12 months, what have you done to protect yourself/family against tick bites or tick-borne diseases?",
        bl_vbd_meas_tick___1       = "Check for and remove ticks after outdoor activities",
        bl_vbd_meas_tick___2       = "Wear protective clothing",
        bl_vbd_meas_tick___3       = "Use insect repellent on skin or clothing",
        bl_vbd_meas_tick___4       = "Avoid wooded areas during tick activity",
        bl_vbd_meas_tick___88      = "Other measure: {bl_vbd_oth_meas}",
        bl_vbd_meas_tick___0       = "No active measures",
        bl_vbd_meas_mosq           = "In the last 12 months, what have you done to protect yourself/family against mosquito bites?",
        bl_vbd_meas_mosq___1       = "Use repellent",
        bl_vbd_meas_mosq___2       = "Wear protective clothing",
        bl_vbd_meas_mosq___3       = "Burn mosquito coils",
        bl_vbd_meas_mosq___4       = "Stay in screened areas",
        bl_vbd_meas_mosq___5       = "Install window screens",
        bl_vbd_meas_mosq___6       = "Use fans",
        bl_vbd_meas_mosq___7       = "Use automatic insect spray",
        bl_vbd_meas_mosq___8       = "Install bed nets",
        bl_vbd_meas_mosq___9       = "Remove containers with standing water",
        bl_vbd_meas_mosq___88      = "Other measure: {bl_vbd_oth_meas_0}",
        bl_vbd_meas_mosq___0       = "No active measures",
        bl_vbd_meas_tick_eff       = "Which of these do you think effectively protect the public against tick-borne diseases?",
        bl_vbd_meas_tick_eff___1   = "Apply environmental pesticides",
        bl_vbd_meas_tick_eff___2   = "Use biological control (e.g. predators)",
        bl_vbd_meas_tick_eff___3   = "Clear vegetation in woods",
        bl_vbd_meas_tick_eff___4   = "Protect deer from ticks",
        bl_vbd_meas_tick_eff___5   = "Control deer numbers in public woods",
        bl_vbd_meas_tick_eff___6   = "Block deer from public woods",
        bl_vbd_meas_tick_eff___7   = "Protect small rodents from ticks",
        bl_vbd_meas_tick_eff___8   = "Promote personal protective measures",
        bl_vbd_meas_tick_eff___0   = "None of these",
        bl_vbd_meas_mosq_eff       = "Which of these do you think effectively protect the public against mosquito-borne diseases?",
        bl_vbd_meas_mosq_eff___1   = "Apply environmental pesticides",
        bl_vbd_meas_mosq_eff___2   = "Use biological control (e.g. predators)",
        bl_vbd_meas_mosq_eff___3   = "Eliminate standing water in containers",
        bl_vbd_meas_mosq_eff___4   = "Apply larvicides",
        bl_vbd_meas_mosq_eff___5   = "Install repellent sprayers",
        bl_vbd_meas_mosq_eff___6   = "Install mosquito traps",
        bl_vbd_meas_mosq_eff___7   = "Release irradiated or GM mosquitoes",
        bl_vbd_meas_mosq_eff___8   = "Promote personal protective measures",
        bl_vbd_meas_mosq_eff___0   = "None of these",
        bl_vbd_dis_problem         = "Do you consider the following a current health problem in Switzerland?",
        bl_vbd_dis_problem___1     = "Tick-borne encephalitis",
        bl_vbd_dis_problem___2     = "West Nile fever",
        bl_vbd_dis_problem___3     = "Dengue",
        bl_vbd_dis_problem___4     = "Zika",
        bl_vbd_dis_problem___5     = "Chikungunya",
        bl_vbd_dis_problem___6     = "Lyme disease",
        bl_vbd_meth_yn             = "Do you think vector control measures are necessary in Switzerland?",
        isco_lvl1                  = "Industry according to CH-ISCO 2019"
      ) %>%
      # value labels
      labelled::set_value_labels(
        bl_sex                    = c("Female"=2, "Male"=1, "Intersex"=3),
        bl_gender_def             = c("Female"=2, "Male"=1, "Other, please specify..."=3),
        bl_commune                = value_commune,
        bl_live_ch_since          = c("Since birth"=1, "Born in Switzerland but also lived abroad"=2, "Born abroad"=3),
        bl_education              = c(
          "None"=0, "Incomplete compulsory schooling"=1, "Compulsory schooling"=2,
          "One-year transitional program"=3, "General education school"=4,
          "Apprenticeship/vocational school"=5, "Gymnasial maturity"=6,
          "Professional maturity"=7, "Federal diploma exam"=8,
          "Higher vocational school"=9, "Bachelor degree"=10,
          "Master degree"=11, "Doctorate/habilitation"=12
        ),
        bl_scg_marital_status     = c(
          "Married, living with spouse"=1, "Married, permanently separated"=2,
          "Registered partnership, living together"=3, "Registered partnership, separated"=4,
          "Single, stable partnership"=5, "Single, living alone"=6,
          "Divorced"=7, "Widowed"=8
        ),
        bl_vacc_yn                = c("Yes"=1, "No"=0),
        bl_ppre_challenge___1     = c("Yes"=1, "No"=0),
        bl_ppre_challenge___2     = c("Yes"=1, "No"=0),
        bl_ppre_challenge___3     = c("Yes"=1, "No"=0),
        bl_ppre_challenge___4     = c("Yes"=1, "No"=0),
        bl_ppre_challenge___5     = c("Yes"=1, "No"=0),
        bl_ppre_challenge___6     = c("Yes"=1, "No"=0),
        bl_ppre_challenge___7     = c("Yes"=1, "No"=0),
        bl_abroad_yn              = c("Yes"=1, "No"=0),
        bl_continent___1          = c("Yes"=1, "No"=0),
        bl_continent___2          = c("Yes"=1, "No"=0),
        bl_continent___3          = c("Yes"=1, "No"=0),
        bl_continent___4          = c("Yes"=1, "No"=0),
        bl_continent___5          = c("Yes"=1, "No"=0),
        bl_continent___6          = c("Yes"=1, "No"=0),
        bl_continent___7          = c("Yes"=1, "No"=0),
        bl_vbd_tick_yn            = c("Yes"=1, "No"=0),
        bl_vbd_diseases___1       = c("Yes"=1, "No"=0),
        bl_vbd_diseases___2       = c("Yes"=1, "No"=0),
        bl_vbd_diseases___3       = c("Yes"=1, "No"=0),
        bl_vbd_diseases___4       = c("Yes"=1, "No"=0),
        bl_vbd_diseases___5       = c("Yes"=1, "No"=0),
        bl_vbd_diseases___6       = c("Yes"=1, "No"=0),
        bl_vbd_diseases___7       = c("Yes"=1, "No"=0),
        bl_vbd_diseases___0       = c("Yes"=1, "No"=0),
        bl_vbd_vector_dis___1     = c("Yes"=1, "No"=0),
        bl_vbd_vector_dis___2     = c("Yes"=1, "No"=0),
        bl_vbd_vector_dis___3     = c("Yes"=1, "No"=0),
        bl_vbd_vector_dis___4     = c("Yes"=1, "No"=0),
        bl_vbd_vector_dis___5     = c("Yes"=1, "No"=0),
        bl_vbd_vector_dis___6     = c("Yes"=1, "No"=0),
        bl_vbd_vector_dis___7     = c("Yes"=1, "No"=0),
        bl_vbd_vector_dis___0     = c("Yes"=1, "No"=0),
        bl_vbd_organism___1       = c("Yes"=1, "No"=0),
        bl_vbd_organism___2       = c("Yes"=1, "No"=0),
        bl_vbd_organism___3       = c("Yes"=1, "No"=0),
        bl_vbd_organism___4       = c("Yes"=1, "No"=0),
        bl_vbd_organism___0       = c("Yes"=1, "No"=0),
        bl_vbd_transmitter___1    = c("Yes"=1, "No"=0),
        bl_vbd_transmitter___2    = c("Yes"=1, "No"=0),
        bl_vbd_transmitter___3    = c("Yes"=1, "No"=0),
        bl_vbd_transmitter___4    = c("Yes"=1, "No"=0),
        bl_vbd_transmitter___0    = c("Yes"=1, "No"=0),
        bl_vbd_tick_enc           = c(
          "Mosquitoes"=1, "Ticks"=2, "Wasps"=3, "Bed bugs"=4,
          "None of these"=0, "I don't know"=99
        ),
        bl_vbd_wnf                = c(
          "Mosquitoes"=1, "Ticks"=2, "Wasps"=3, "Bed bugs"=4,
          "None of these"=0, "I don't know"=99
        ),
        bl_vbd_dengue             = c(
          "Mosquitoes"=1, "Ticks"=2, "Wasps"=3, "Bed bugs"=4,
          "None of these"=0, "I don't know"=99
        ),
        bl_vbd_zika               = c(
          "Mosquitoes"=1, "Ticks"=2, "Wasps"=3, "Bed bugs"=4,
          "None of these"=0, "I don't know"=99
        ),
        bl_vbd_chikun             = c(
          "Mosquitoes"=1, "Ticks"=2, "Wasps"=3, "Bed bugs"=4,
          "None of these"=0, "I don't know"=99
        ),
        bl_vbd_lyme               = c(
          "Mosquitoes"=1, "Ticks"=2, "Wasps"=3, "Bed bugs"=4,
          "None of these"=0, "I don't know"=99
        ),
        bl_vbd_influenza          = c(
          "Mosquitoes"=1, "Ticks"=2, "Wasps"=3, "Bed bugs"=4,
          "None of these"=0, "I don't know"=99
        ),
        bl_vbd_measle             = c(
          "Mosquitoes"=1, "Ticks"=2, "Wasps"=3, "Bed bugs"=4,
          "None of these"=0, "I don't know"=99
        ),
        bl_vbd_tickbite_nr        = c("0"=0, "1–3"=1, "4–6"=2, "7–9"=3, "10+"=4),
        bl_vbd_mosqbite_nr        = c(
          "Every day"=1, "At least weekly"=2, "At least monthly"=3,
          "At least yearly"=4, "Less than yearly"=5, "Never"=0, "I don't know"=99
        ),
        bl_vbd_meas_tick___1      = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick___2      = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick___3      = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick___4      = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick___88     = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick___0      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___1      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___2      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___3      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___4      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___5      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___6      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___7      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___8      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___9      = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___88     = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq___0      = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___1  = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___2  = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___3  = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___4  = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___5  = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___6  = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___7  = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___8  = c("Yes"=1, "No"=0),
        bl_vbd_meas_tick_eff___0  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___1  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___2  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___3  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___4  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___5  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___6  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___7  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___8  = c("Yes"=1, "No"=0),
        bl_vbd_meas_mosq_eff___0  = c("Yes"=1, "No"=0),
        bl_vbd_dis_problem___1    = c("Yes"=1, "No"=0),
        bl_vbd_dis_problem___2    = c("Yes"=1, "No"=0),
        bl_vbd_dis_problem___3    = c("Yes"=1, "No"=0),
        bl_vbd_dis_problem___4    = c("Yes"=1, "No"=0),
        bl_vbd_dis_problem___5    = c("Yes"=1, "No"=0),
        bl_vbd_dis_problem___6    = c("Yes"=1, "No"=0),
        bl_vbd_meth_yn            = c("Yes"=1, "No"=0, "Don't know"=99)
      )
  }
  
  dat1 = dat0 %>%
    dplyr::mutate(
      bl_sex                   = labelled::to_factor(bl_sex),
      bl_gender_def            = labelled::to_factor(bl_gender_def),
      bl_commune               = labelled::to_factor(bl_commune),
      bl_live_ch_since         = labelled::to_factor(bl_live_ch_since),
      bl_education             = labelled::to_factor(bl_education),
      bl_scg_marital_status    = labelled::to_factor(bl_scg_marital_status),
      bl_vacc_yn               = labelled::to_factor(bl_vacc_yn),
      bl_abroad_yn             = labelled::to_factor(bl_abroad_yn),
      bl_continent___1         = labelled::to_factor(bl_continent___1),
      bl_continent___2         = labelled::to_factor(bl_continent___2),
      bl_continent___3         = labelled::to_factor(bl_continent___3),
      bl_continent___4         = labelled::to_factor(bl_continent___4),
      bl_continent___5         = labelled::to_factor(bl_continent___5),
      bl_continent___6         = labelled::to_factor(bl_continent___6),
      bl_continent___7         = labelled::to_factor(bl_continent___7),
      bl_vbd_tick_yn           = labelled::to_factor(bl_vbd_tick_yn),
      bl_vbd_diseases___1      = labelled::to_factor(bl_vbd_diseases___1),
      bl_vbd_diseases___2      = labelled::to_factor(bl_vbd_diseases___2),
      bl_vbd_diseases___3      = labelled::to_factor(bl_vbd_diseases___3),
      bl_vbd_diseases___4      = labelled::to_factor(bl_vbd_diseases___4),
      bl_vbd_diseases___5      = labelled::to_factor(bl_vbd_diseases___5),
      bl_vbd_diseases___6      = labelled::to_factor(bl_vbd_diseases___6),
      bl_vbd_diseases___7      = labelled::to_factor(bl_vbd_diseases___7),
      bl_vbd_diseases___0      = labelled::to_factor(bl_vbd_diseases___0),
      bl_vbd_vector_dis___1    = labelled::to_factor(bl_vbd_vector_dis___1),
      bl_vbd_vector_dis___2    = labelled::to_factor(bl_vbd_vector_dis___2),
      bl_vbd_vector_dis___3    = labelled::to_factor(bl_vbd_vector_dis___3),
      bl_vbd_vector_dis___4    = labelled::to_factor(bl_vbd_vector_dis___4),
      bl_vbd_vector_dis___5    = labelled::to_factor(bl_vbd_vector_dis___5),
      bl_vbd_vector_dis___6    = labelled::to_factor(bl_vbd_vector_dis___6),
      bl_vbd_vector_dis___7    = labelled::to_factor(bl_vbd_vector_dis___7),
      bl_vbd_vector_dis___0    = labelled::to_factor(bl_vbd_vector_dis___0),
      bl_vbd_organism___1      = labelled::to_factor(bl_vbd_organism___1),
      bl_vbd_organism___2      = labelled::to_factor(bl_vbd_organism___2),
      bl_vbd_organism___3      = labelled::to_factor(bl_vbd_organism___3),
      bl_vbd_organism___4      = labelled::to_factor(bl_vbd_organism___4),
      bl_vbd_organism___0      = labelled::to_factor(bl_vbd_organism___0),
      bl_vbd_transmitter___1   = labelled::to_factor(bl_vbd_transmitter___1),
      bl_vbd_transmitter___2   = labelled::to_factor(bl_vbd_transmitter___2),
      bl_vbd_transmitter___3   = labelled::to_factor(bl_vbd_transmitter___3),
      bl_vbd_transmitter___4   = labelled::to_factor(bl_vbd_transmitter___4),
      bl_vbd_transmitter___0   = labelled::to_factor(bl_vbd_transmitter___0),
      bl_vbd_tick_enc          = labelled::to_factor(bl_vbd_tick_enc),
      bl_vbd_wnf               = labelled::to_factor(bl_vbd_wnf),
      bl_vbd_dengue            = labelled::to_factor(bl_vbd_dengue),
      bl_vbd_zika              = labelled::to_factor(bl_vbd_zika),
      bl_vbd_chikun            = labelled::to_factor(bl_vbd_chikun),
      bl_vbd_lyme              = labelled::to_factor(bl_vbd_lyme),
      bl_vbd_influenza         = labelled::to_factor(bl_vbd_influenza),
      bl_vbd_measle            = labelled::to_factor(bl_vbd_measle),
      bl_vbd_tickbite_nr       = labelled::to_factor(bl_vbd_tickbite_nr),
      bl_vbd_mosqbite_nr       = labelled::to_factor(bl_vbd_mosqbite_nr),
      bl_vbd_meas_tick___1     = labelled::to_factor(bl_vbd_meas_tick___1),
      bl_vbd_meas_tick___2     = labelled::to_factor(bl_vbd_meas_tick___2),
      bl_vbd_meas_tick___3     = labelled::to_factor(bl_vbd_meas_tick___3),
      bl_vbd_meas_tick___4     = labelled::to_factor(bl_vbd_meas_tick___4),
      bl_vbd_meas_tick___88    = labelled::to_factor(bl_vbd_meas_tick___88),
      bl_vbd_meas_tick___0     = labelled::to_factor(bl_vbd_meas_tick___0),
      bl_vbd_meas_mosq___1     = labelled::to_factor(bl_vbd_meas_mosq___1),
      bl_vbd_meas_mosq___2     = labelled::to_factor(bl_vbd_meas_mosq___2),
      bl_vbd_meas_mosq___3     = labelled::to_factor(bl_vbd_meas_mosq___3),
      bl_vbd_meas_mosq___4     = labelled::to_factor(bl_vbd_meas_mosq___4),
      bl_vbd_meas_mosq___5     = labelled::to_factor(bl_vbd_meas_mosq___5),
      bl_vbd_meas_mosq___6     = labelled::to_factor(bl_vbd_meas_mosq___6),
      bl_vbd_meas_mosq___7     = labelled::to_factor(bl_vbd_meas_mosq___7),
      bl_vbd_meas_mosq___8     = labelled::to_factor(bl_vbd_meas_mosq___8),
      bl_vbd_meas_mosq___9     = labelled::to_factor(bl_vbd_meas_mosq___9),
      bl_vbd_meas_mosq___88    = labelled::to_factor(bl_vbd_meas_mosq___88),
      bl_vbd_meas_mosq___0     = labelled::to_factor(bl_vbd_meas_mosq___0),
      bl_vbd_meas_tick_eff___1 = labelled::to_factor(bl_vbd_meas_tick_eff___1),
      bl_vbd_meas_tick_eff___2 = labelled::to_factor(bl_vbd_meas_tick_eff___2),
      bl_vbd_meas_tick_eff___3 = labelled::to_factor(bl_vbd_meas_tick_eff___3),
      bl_vbd_meas_tick_eff___4 = labelled::to_factor(bl_vbd_meas_tick_eff___4),
      bl_vbd_meas_tick_eff___5 = labelled::to_factor(bl_vbd_meas_tick_eff___5),
      bl_vbd_meas_tick_eff___6 = labelled::to_factor(bl_vbd_meas_tick_eff___6),
      bl_vbd_meas_tick_eff___7 = labelled::to_factor(bl_vbd_meas_tick_eff___7),
      bl_vbd_meas_tick_eff___8 = labelled::to_factor(bl_vbd_meas_tick_eff___8),
      bl_vbd_meas_tick_eff___0 = labelled::to_factor(bl_vbd_meas_tick_eff___0),
      bl_vbd_meas_mosq_eff___1 = labelled::to_factor(bl_vbd_meas_mosq_eff___1),
      bl_vbd_meas_mosq_eff___2 = labelled::to_factor(bl_vbd_meas_mosq_eff___2),
      bl_vbd_meas_mosq_eff___3 = labelled::to_factor(bl_vbd_meas_mosq_eff___3),
      bl_vbd_meas_mosq_eff___4 = labelled::to_factor(bl_vbd_meas_mosq_eff___4),
      bl_vbd_meas_mosq_eff___5 = labelled::to_factor(bl_vbd_meas_mosq_eff___5),
      bl_vbd_meas_mosq_eff___6 = labelled::to_factor(bl_vbd_meas_mosq_eff___6),
      bl_vbd_meas_mosq_eff___7 = labelled::to_factor(bl_vbd_meas_mosq_eff___7),
      bl_vbd_meas_mosq_eff___8 = labelled::to_factor(bl_vbd_meas_mosq_eff___8),
      bl_vbd_meas_mosq_eff___0 = labelled::to_factor(bl_vbd_meas_mosq_eff___0),
      bl_vbd_dis_problem___1   = labelled::to_factor(bl_vbd_dis_problem___1),
      bl_vbd_dis_problem___2   = labelled::to_factor(bl_vbd_dis_problem___2),
      bl_vbd_dis_problem___3   = labelled::to_factor(bl_vbd_dis_problem___3),
      bl_vbd_dis_problem___4   = labelled::to_factor(bl_vbd_dis_problem___4),
      bl_vbd_dis_problem___5   = labelled::to_factor(bl_vbd_dis_problem___5),
      bl_vbd_dis_problem___6   = labelled::to_factor(bl_vbd_dis_problem___6),
      bl_vbd_meth_yn           = labelled::to_factor(bl_vbd_meth_yn)
    )
  
  # Return
  dat_out = dat1
  return(dat_out)
}



