#' ---
#' title: VBD surveys 
#' subtitle: Labels in german (official), french or english (AI translation)
#' author: jriou
#' date: 2025-06-10
#' ---

sh_002_labels = function(dat_in, lang){
  
  if(lang == "FR") {
    Sys.setlocale("LC_ALL", "fr_FR.UTF-8")
    dat0 = dat_in %>%
      # étiquettes des variables
      labelled::set_variable_labels(
        type = "Service",
        b_1 = "Votre autorité s'engage-t-elle actuellement dans la mise en œuvre de mesures ou d'activités (par exemple, travail de sensibilisation, surveillance ou lutte) dans le domaine des maladies transmises par les tiques et les moustiques ?",
        b_1_1___1 = "L'introduction de mesures/activités dans le domaine des maladies transmises par les tiques et les moustiques est actuellement en cours d'examen/planification.",
        b_1_1___2 = "Les maladies transmises par les tiques et les moustiques ne sont pas considérées comme faisant partie du domaine de responsabilité de votre autorité.",
        b_1_1___3 = "Les maladies transmises par les tiques et les moustiques n'ont pas une priorité élevée dans votre autorité.",
        b_1_1___4 = "Le nombre de cas de maladies transmises par les tiques et les moustiques n'est pas encore une préoccupation suffisamment importante pour déclencher des mesures dans mon domaine.",
        b_1_1___5 = "Manque de ressources financières et/ou humaines.",
        b_1_1___6 = "Manque de personnel qualifié.",
        b_1_1___7 = "Manque d'intérêt public.",
        b_1_1___8 = "Décision/mandat politique manquant.",
        b_1_1___9 = "Manque de lignes directrices/nationales/bases/recommandations sur lesquelles s'orienter.",
        b_1_1___10 = "Aucune indication / ne sait pas",
        b_1_1___11 = "Autres raisons",
        b_1_2 = "B.1.2. Si d'autres raisons dans B.1.1 : Lesquelles ?",
        b_2___1 = "Oui, pour les maladies transmises par les tiques",
        b_2___2 = "Oui, pour les maladies transmises par les moustiques",
        b_2___3 = "Non, ni pour les maladies transmises par les tiques ni pour celles transmises par les moustiques",
        b_2___4 = "Aucune indication / ne sait pas",
        b_2_1 = "B.2.1. Si Oui dans B.2 : Pouvez-vous le décrire/le lier ?",
        b_3___1 = "Oui, pour les maladies transmises par les tiques",
        b_3___2 = "Oui, pour les maladies transmises par les moustiques",
        b_3___3 = "Non, ni pour les maladies transmises par les tiques ni pour celles transmises par les moustiques",
        b_3___4 = "Aucune indication / ne sait pas",
        b_3_1 = "B.3.1. Si Oui : Quelle est l'étendue des pourcentages de postes actuels ?",
        b_4___1 = "Oui, pour les maladies transmises par les tiques",
        b_4___2 = "Oui, pour les maladies transmises par les moustiques",
        b_4___3 = "Non, ni pour les maladies transmises par les tiques ni pour celles transmises par les moustiques",
        b_4___4 = "Aucune indication / ne sait pas",
        c_1___1 = "Travail de sensibilisation (diffusion de matériel éducatif sur les maladies transmises par les tiques à la population générale)",
        c_1___2 = "Sensibilisation ciblée des professionnels (documents sur les maladies transmises par les tiques)",
        c_1___3 = "Conseil en vaccination pour la population (par le personnel de santé)",
        c_1___4 = "Conseil pour les propriétaires de maisons sur la gestion des tiques sur leur propriété",
        c_1___5 = "Surveillance active des tiques (collecte de tiques sur le terrain pour identification, examen ou analyse)",
        c_1___6 = "Surveillance passive des tiques (acceptation d'échantillons de tiques soumis par le public, les vétérinaires, les médecins, etc., pour identification, examen ou analyse)",
        c_1___7 = "Formations et publication de matériel pédagogique",
        c_1___8 = "Aucune indication / ne sait pas",
        c_1___9 = "Autre : réponse ouverte",
        c_1___10 = "Mon autorité ne mène aucune activité pour les maladies transmises par les tiques",
        c_1_1 = "Réponse ouverte",
        c_2___1 = "Travail de sensibilisation (diffusion de matériel éducatif sur les maladies transmises par les moustiques à la population générale)",
        c_2___2 = "Sensibilisation ciblée des professionnels (documents sur les maladies transmises par les moustiques)",
        c_2___3 = "Surveillance active des moustiques (collecte de moustiques à l'aide de pièges pour identification et diagnostic, par exemple, Ovitraps)",
        c_2___4 = "Surveillance passive des moustiques (acceptation d'envois et de signalements de moustiques directement du public ou via le réseau suisse des moustiques)",
        c_2___5 = "Vérification des signalements de moustiques dans de nouveaux lieux de découverte",
        c_2___6 = "Lutte contre les moustiques sur les terres publiques",
        c_2___7 = "Lutte contre les moustiques sur les propriétés privées",
        c_2___8 = "Formations et publication de matériel pédagogique",
        c_2___9 = "Aucune indication / ne sait pas",
        c_2___10 = "Autre : réponse ouverte",
        c_2___11 = "Mon autorité ne mène aucune activité pour les maladies transmises par les moustiques",
        c_2_1 = "Réponse ouverte",
        c_3___1 = "Retrait correct des tiques",
        c_3___2 = "Élimination des sites de reproduction des moustiques",
        c_3___3 = "Vaccinations",
        c_3___4 = "Informations sur les sprays contre les moustiques/tiques",
        c_3___5 = "Protection contre les piqûres/morsures",
        c_3___6 = "Sensibilisation à la surveillance attentive des symptômes",
        c_3___7 = "Informations sur les zones à risque",
        c_3___8 = "Informations sur l'installation correcte des moustiquaires",
        c_3___9 = "Aucune indication / ne sait pas",
        c_3___10 = "Autre : réponse ouverte",
        c_3_1 = "Réponse ouverte",
        c_4 = "C.4. Comment diffusez-vous ces informations (par exemple, site web, flyers, événements d'information, formations) ?",
        c_5 = "C.5. Quelles lignes directrices / matériel d'aide / documents de référence existants (par exemple, de la Confédération, d'autres cantons, d'organisations nationales ou internationales) utilisez-vous / votre autorité utilise-t-elle pour le développement et la mise en œuvre de mesures ?",
        c_6___1 = "Prévention des maladies transmises par les tiques",
        c_6___2 = "Détection des tiques et des agents pathogènes dans les tiques",
        c_6___3 = "Diagnostic des maladies transmises par les tiques",
        c_6___4 = "Gestion et contrôle/lutte concernant les maladies transmises par les tiques",
        c_6___5 = "Traitement/thérapie des maladies transmises par les tiques",
        c_6___6 = "Autre : réponse ouverte",
        c_6_1 = "Réponse ouverte",
        c_7___1 = "Prévention des maladies transmises par les moustiques",
        c_7___2 = "Détection des moustiques invasifs et des agents pathogènes dans les moustiques",
        c_7___3 = "Diagnostic des maladies transmises par les moustiques",
        c_7___4 = "Gestion et contrôle/lutte concernant les moustiques/maladies transmises par les moustiques",
        c_7___5 = "Traitement/thérapie des maladies transmises par les moustiques",
        c_7___6 = "Autre : réponse ouverte",
        c_7_1 = "Réponse ouverte",
        c_8___1 = "Adulticides (Pyréthroïdes)",
        c_8___2 = "Larvicides non chimiques",
        c_8___3 = "Larvicides biologiques",
        c_8___4 = "Élimination des sites de reproduction",
        c_8___5 = "Stérilisation des moustiques",
        c_8___6 = "Aucun",
        c_8___7 = "Autre : réponse ouverte",
        c_8_1 = "Réponse ouverte",
        d_1___1 = "Oui, pour les maladies transmises par les tiques",
        d_1___2 = "Oui, pour les maladies transmises par les moustiques",
        d_1___3 = "Non, ni pour les maladies transmises par les tiques ni pour celles transmises par les moustiques",
        d_1___4 = "Aucune indication / ne sait pas",
        d_2 = "D.2. Selon vous, où existe-t-il un besoin de soutien des cantons par la Confédération dans le domaine des maladies transmises par les tiques et les moustiques ?",
        d_3___1 = "Oui, suffisant pour les maladies transmises par les tiques",
        d_3___2 = "Oui, suffisant pour les maladies transmises par les moustiques",
        d_3___3 = "Insuffisant pour les maladies transmises par les tiques",
        d_3___4 = "Insuffisant pour les maladies transmises par les moustiques",
        d_3___5 = "Non, ni pour les maladies transmises par les tiques ni pour celles transmises par les moustiques",
        d_3___6 = "Aucune indication / ne sait pas",
        d_4___1 = "Oui, suffisant pour les maladies transmises par les tiques",
        d_4___2 = "Oui, suffisant pour les maladies transmises par les moustiques",
        d_4___3 = "Insuffisant pour les maladies transmises par les tiques",
        d_4___4 = "Insuffisant pour les maladies transmises par les moustiques",
        d_4___5 = "Non, ni pour les maladies transmises par les tiques ni pour celles transmises par les moustiques",
        d_4___6 = "Aucune indication / ne sait pas"
      ) %>%
      # étiquettes de valeurs
      labelled::set_value_labels(
        type= c("Santé humaine"="M","Santé animale"="T","Environnement"="U"),
        b_1 = c("Oui" = 1, "Non" = 2, "Aucune indication / ne sait pas" = 3),
        b_1_1___1 = c("Oui" = 1, "Non" = 0),
        b_1_1___2 = c("Oui" = 1, "Non" = 0),
        b_1_1___3 = c("Oui" = 1, "Non" = 0),
        b_1_1___4 = c("Oui" = 1, "Non" = 0),
        b_1_1___5 = c("Oui" = 1, "Non" = 0),
        b_1_1___6 = c("Oui" = 1, "Non" = 0),
        b_1_1___7 = c("Oui" = 1, "Non" = 0),
        b_1_1___8 = c("Oui" = 1, "Non" = 0),
        b_1_1___9 = c("Oui" = 1, "Non" = 0),
        b_1_1___10 = c("Oui" = 1, "Non" = 0),
        b_1_1___11 = c("Oui" = 1, "Non" = 0),
        b_2___1 = c("Oui" = 1, "Non" = 0),
        b_2___2 = c("Oui" = 1, "Non" = 0),
        b_2___3 = c("Oui" = 1, "Non" = 0),
        b_2___4 = c("Oui" = 1, "Non" = 0),
        b_3___1 = c("Oui" = 1, "Non" = 0),
        b_3___2 = c("Oui" = 1, "Non" = 0),
        b_3___3 = c("Oui" = 1, "Non" = 0),
        b_3___4 = c("Oui" = 1, "Non" = 0),
        b_4___1 = c("Oui" = 1, "Non" = 0),
        b_4___2 = c("Oui" = 1, "Non" = 0),
        b_4___3 = c("Oui" = 1, "Non" = 0),
        b_4___4 = c("Oui" = 1, "Non" = 0),
        c_1___1 = c("Oui" = 1, "Non" = 0),
        c_1___2 = c("Oui" = 1, "Non" = 0),
        c_1___3 = c("Oui" = 1, "Non" = 0),
        c_1___4 = c("Oui" = 1, "Non" = 0),
        c_1___5 = c("Oui" = 1, "Non" = 0),
        c_1___6 = c("Oui" = 1, "Non" = 0),
        c_1___7 = c("Oui" = 1, "Non" = 0),
        c_1___8 = c("Oui" = 1, "Non" = 0),
        c_1___9 = c("Oui" = 1, "Non" = 0),
        c_1___10 = c("Oui" = 1, "Non" = 0),
        c_2___1 = c("Oui" = 1, "Non" = 0),
        c_2___2 = c("Oui" = 1, "Non" = 0),
        c_2___3 = c("Oui" = 1, "Non" = 0),
        c_2___4 = c("Oui" = 1, "Non" = 0),
        c_2___5 = c("Oui" = 1, "Non" = 0),
        c_2___6 = c("Oui" = 1, "Non" = 0),
        c_2___7 = c("Oui" = 1, "Non" = 0),
        c_2___8 = c("Oui" = 1, "Non" = 0),
        c_2___9 = c("Oui" = 1, "Non" = 0),
        c_2___10 = c("Oui" = 1, "Non" = 0),
        c_2___11 = c("Oui" = 1, "Non" = 0),
        c_3___1 = c("Oui" = 1, "Non" = 0),
        c_3___2 = c("Oui" = 1, "Non" = 0),
        c_3___3 = c("Oui" = 1, "Non" = 0),
        c_3___4 = c("Oui" = 1, "Non" = 0),
        c_3___5 = c("Oui" = 1, "Non" = 0),
        c_3___6 = c("Oui" = 1, "Non" = 0),
        c_3___7 = c("Oui" = 1, "Non" = 0),
        c_3___8 = c("Oui" = 1, "Non" = 0),
        c_3___9 = c("Oui" = 1, "Non" = 0),
        c_3___10 = c("Oui" = 1, "Non" = 0),
        c_6___1 = c("Oui" = 1, "Non" = 0),
        c_6___2 = c("Oui" = 1, "Non" = 0),
        c_6___3 = c("Oui" = 1, "Non" = 0),
        c_6___4 = c("Oui" = 1, "Non" = 0),
        c_6___5 = c("Oui" = 1, "Non" = 0),
        c_6___6 = c("Oui" = 1, "Non" = 0),
        c_7___1 = c("Oui" = 1, "Non" = 0),
        c_7___2 = c("Oui" = 1, "Non" = 0),
        c_7___3 = c("Oui" = 1, "Non" = 0),
        c_7___4 = c("Oui" = 1, "Non" = 0),
        c_7___5 = c("Oui" = 1, "Non" = 0),
        c_7___6 = c("Oui" = 1, "Non" = 0),
        c_8___1 = c("Oui" = 1, "Non" = 0),
        c_8___2 = c("Oui" = 1, "Non" = 0),
        c_8___3 = c("Oui" = 1, "Non" = 0),
        c_8___4 = c("Oui" = 1, "Non" = 0),
        c_8___5 = c("Oui" = 1, "Non" = 0),
        c_8___6 = c("Oui" = 1, "Non" = 0),
        c_8___7 = c("Oui" = 1, "Non" = 0),
        d_1___1 = c("Oui" = 1, "Non" = 0),
        d_1___2 = c("Oui" = 1, "Non" = 0),
        d_1___3 = c("Oui" = 1, "Non" = 0),
        d_1___4 = c("Oui" = 1, "Non" = 0),
        d_3___1 = c("Oui" = 1, "Non" = 0),
        d_3___2 = c("Oui" = 1, "Non" = 0),
        d_3___3 = c("Oui" = 1, "Non" = 0),
        d_3___4 = c("Oui" = 1, "Non" = 0),
        d_3___5 = c("Oui" = 1, "Non" = 0),
        d_3___6 = c("Oui" = 1, "Non" = 0),
        d_4___1 = c("Oui" = 1, "Non" = 0),
        d_4___2 = c("Oui" = 1, "Non" = 0),
        d_4___3 = c("Oui" = 1, "Non" = 0),
        d_4___4 = c("Oui" = 1, "Non" = 0),
        d_4___5 = c("Oui" = 1, "Non" = 0),
        d_4___6 = c("Oui" = 1, "Non" = 0)
      ) 
  }
  
  if(lang=="DE") {
    Sys.setlocale("LC_ALL", "de_DE.UTF-8")
    dat0 = dat_in %>%
      # variable labels
      labelled::set_variable_labels(
        type = "Amt",
        b_1 = "B.1. Engagiert sich Ihre Behörde aktuell bei der Umsetzung von Massnahmen bzw. Aktivitäten (z.B. Öffentlichkeitsarbeit, Überwachung oder Bekämpfung) im Bereich der durch Zecken und Mücken übertragenen Krankheiten?",
        b_1_1___1 = "Die Einführung von Massnahmen / Aktivitäten im Bereich der durch Zecken und Mücken übertragenen Krankheiten wird derzeit geprüft/geplant.",
        b_1_1___2 = "Durch Zecken und Mücken übertragene Krankheiten werden nicht als Aufgaben-/Zuständigkeitsbereich Ihrer Behörde betrachtet.",
        b_1_1___3 = "Durch Zecken und Mücken übertragene Krankheiten haben in Ihrer Behörde keine hohe Priorität.",
        b_1_1___4 = "Die Fallzahlen von durch Zecken und Mücken übertragenen Krankheiten sind noch kein so wichtiges Anliegen, dass es Massnahmen in meinem Bereich auslösen würde.",
        b_1_1___5 = "Fehlende finanzielle und/oder personelle Ressourcen.",
        b_1_1___6 = "Fehlendes fachlich ausgebildetes Personal.",
        b_1_1___7 = "Fehlendes öffentliches Interesse.",
        b_1_1___8 = "Fehlender politischer Entscheid / Auftrag.",
        b_1_1___9 = "Fehlende nationale Leitlinien/Grundlagen/Empfehlungen an denen man sich orientieren kann.",
        b_1_1___10 = "Keine Angabe / weiss nicht",
        b_1_1___11 = "Andere Gründe",
        b_1_2 = "B.1.2. Falls andere Gründe in B.1.1: Welche?",
        b_2___1 = "Ja, für zeckenübertragene Krankheiten",
        b_2___2 = "Ja, für mückenübertragene Krankheiten",
        b_2___3 = "Nein, weder für zeckenübertragene noch für mückenübertragene Krankheiten",
        b_2___4 = "Keine Angabe / weiss nicht",
        b_2_1 = "B.2.1. Falls Ja in B.2: Können Sie dies beschreiben/verlinken?",
        b_3___1 = "Ja, für zeckenübertragene Krankheiten",
        b_3___2 = "Ja, für mückenübertragene Krankheiten",
        b_3___3 = "Nein, weder für zeckenübertragene noch für mückenübertragene Krankheiten",
        b_3___4 = "Keine Angabe / weiss nicht",
        b_3_1 = "B.3.1. Falls Ja: Was ist der Umfang der aktuellen Stellenprozente?",
        b_4___1 = "Ja, für zeckenübertragene Krankheiten",
        b_4___2 = "Ja, für mückenübertragene Krankheiten",
        b_4___3 = "Nein, weder für zeckenübertragene noch für mückenübertragene Krankheiten",
        b_4___4 = "Keine Angabe / weiss nicht",
        c_1___1 = "Öffentlichkeitsarbeit (Verbreitung von Aufklärungsmaterial über zeckenübertragene Krankheiten an die allgemeine Bevölkerung)",
        c_1___2 = "Gezielte Sensibilisierung von Fachpersonen (Unterlagen über zeckenübertragene Krankheiten)",
        c_1___3 = "Impfberatung für die Bevölkerung (durch Gesundheitspersonal)",
        c_1___4 = "Beratung für Hausbesitzende zum Zeckenmanagement auf ihrem Grundstück",
        c_1___5 = "Aktive Zeckenüberwachung (Sammeln von Zecken im Feld zur Identifizierung, Untersuchung oder Analyse)",
        c_1___6 = "Passive Zeckenüberwachung (Annahme von Zeckenproben, die von der Öffentlichkeit, Tierärzten, Tierärztinnen, Ärzte, Ärztinnen usw. zur Identifizierung, Untersuchung oder Analyse eingereicht werden)",
        c_1___7 = "Schulungen und Herausgabe von Lernmaterial",
        c_1___8 = "Keine Angabe / weiss nicht",
        c_1___9 = "Sonstiges: offene Antwort",
        c_1___10 = "Meine Behörde führt keine Aktivitäten für zeckenübertragene Krankheiten durch",
        c_1_1 = "Offene Antwort",
        c_2___1 = "Öffentlichkeitsarbeit (Verbreitung von Aufklärungsmaterial über mückenübertragene Krankheiten an die allgemeine Bevölkerung)",
        c_2___2 = "Gezielte Sensibilisierung von Fachpersonen (Unterlagen über mückenübertragene Krankheiten)",
        c_2___3 = "Aktive Mückenüberwachung (Sammeln von Mücken mittels Fallen zur Identifizierung und Diagnostik, Bsp. Ovitraps)",
        c_2___4 = "Passive Mückenüberwachung (Annahme von Mückeneinsendungen und -Sichtungen von der Öffentlichkeit direkt oder über das Schweizerische Mückennetzwerk)",
        c_2___5 = "Überprüfen von Mückensichtungen an neuen Fundorten",
        c_2___6 = "Mückenbekämpfung auf öffentlichem Land",
        c_2___7 = "Mückenbekämpfung auf Privatgrundstücken",
        c_2___8 = "Schulungen und Herausgabe von Lernmaterial",
        c_2___9 = "Keine Angabe / weiss nicht",
        c_2___10 = "Sonstiges: offene Antwort",
        c_2___11 = "Meine Behörde führt keine Aktivitäten für mückenübertragene Krankheiten durch",
        c_2_1 = "Offene Antwort",
        c_3___1 = "Korrekte Entfernung von Zecken",
        c_3___2 = "Brutstätteneliminierung bei Mücken",
        c_3___3 = "Impfungen",
        c_3___4 = "Informationen zu Mücken-/Zeckensprays",
        c_3___5 = "Schutz vor Bissen/Stichen",
        c_3___6 = "Sensibilisierung für sorgfältige Symptomüberwachung",
        c_3___7 = "Informationen zu Risikogebieten",
        c_3___8 = "Informationen zur korrekten Installation von Mückennetzen",
        c_3___9 = "Keine Angabe / weiss nicht",
        c_3___10 = "Sonstiges: offene Antwort",
        c_3_1 = "Offene Antwort",
        c_4 = "C.4. Wie verbreiten Sie diese Informationen (Bsp. Webseite, Flyer, Informationsveranstaltungen, Schulungen)?",
        c_5 = "C.5. Welche bestehenden Guidelines / Hilfsmaterialien / Referenzdokumente (z.B. vom Bund, von anderen Kantonen, von nationalen oder internationalen Organisationen) verwenden Sie / verwendet Ihre Behörde für die Entwicklung und Umsetzung von Massnahmen?",
        c_6___1 = "Prävention zeckenübertragenen Krankheiten",
        c_6___2 = "Nachweis von Zecken und von Krankheitserregern in Zecken",
        c_6___3 = "Diagnostik von zeckenübertragenen Krankheiten",
        c_6___4 = "Management und Kontrolle/Bekämpfung betreffend zeckenübertragene Krankheiten",
        c_6___5 = "Therapie/Behandlung von zeckenübertragenen Krankheiten",
        c_6___6 = "Sonstiges: offene Antwort",
        c_6_1 = "Offene Antwort",
        c_7___1 = "Prävention von mückenübertragenen Krankheiten",
        c_7___2 = "Nachweis von invasiven Mücken und von Krankheitserregern in Mücken",
        c_7___3 = "Diagnostik von mückenübertragenen Krankheiten",
        c_7___4 = "Management und Kontrolle/Bekämpfung betreffend Mücken/ mückenübertragenen Krankheiten",
        c_7___5 = "Therapie/Behandlung von mückenübertragenen Krankheiten",
        c_7___6 = "Sonstiges: offene Antwort",
        c_7_1 = "Offene Antwort",
        c_8___1 = "Adultizide (Pyrethroide)",
        c_8___2 = "Nicht-chemische Larvizide",
        c_8___3 = "Biologische Larvizide",
        c_8___4 = "Beseitigung von Brutstätten",
        c_8___5 = "Sterilisierung von Mücken",
        c_8___6 = "Keine",
        c_8___7 = "Sonstiges: offene Antwort",
        c_8_1 = "Offene Antwort",
        d_1___1 = "Ja, für zeckenübertragene Krankheiten",
        d_1___2 = "Ja, für mückenübertragene Krankheiten",
        d_1___3 = "Nein, weder für zeckenübertragene noch für mückenübertragene Krankheiten",
        d_1___4 = "Keine Angabe / weiss nicht",
        d_2 = "D.2. Wo besteht Ihrer Meinung nach Bedarf für Unterstützung der Kantone durch den Bund im Bereich der durch Zecken und Mücken übertragenen Krankheiten.",
        d_3___1 = "Ja, ausreichend für zeckenübertragene Krankheiten",
        d_3___2 = "Ja, ausreichend für mückenübertragene Krankheiten",
        d_3___3 = "Zu wenig für zeckenübertragene Krankheiten",
        d_3___4 = "Zu wenig für mückenübertragene Krankheiten",
        d_3___5 = "Nein, weder für zeckenübertragene noch für mückenübertragene Krankheiten",
        d_3___6 = "Keine Angabe / weiss nicht",
        d_4___1 = "Ja, ausreichend für zeckenübertragene Krankheiten",
        d_4___2 = "Ja, ausreichend für mückenübertragene Krankheiten",
        d_4___3 = "Zu wenig für zeckenübertragene Krankheiten",
        d_4___4 = "Zu wenig für mückenübertragene Krankheiten",
        d_4___5 = "Nein, weder für zeckenübertragene noch für mückenübertragene Krankheiten",
        d_4___6 = "Keine Angabe / weiss nicht"
      ) %>%
      # value labels
      labelled::set_value_labels(
        type= c("Menschliche Gesundheit"="M","Tiergesundheit"="T","Umwelt"="U"),
        b_1 = c("Ja" = 1, "Nein" = 2, "Keine Angabe / weiss nicht" = 3),
        b_1_1___1 = c("Ja" = 1, "Nein" = 0),
        b_1_1___2 = c("Ja" = 1, "Nein" = 0),
        b_1_1___3 = c("Ja" = 1, "Nein" = 0),
        b_1_1___4 = c("Ja" = 1, "Nein" = 0),
        b_1_1___5 = c("Ja" = 1, "Nein" = 0),
        b_1_1___6 = c("Ja" = 1, "Nein" = 0),
        b_1_1___7 = c("Ja" = 1, "Nein" = 0),
        b_1_1___8 = c("Ja" = 1, "Nein" = 0),
        b_1_1___9 = c("Ja" = 1, "Nein" = 0),
        b_1_1___10 = c("Ja" = 1, "Nein" = 0),
        b_1_1___11 = c("Ja" = 1, "Nein" = 0),
        b_2___1 = c("Ja" = 1, "Nein" = 0),
        b_2___2 = c("Ja" = 1, "Nein" = 0),
        b_2___3 = c("Ja" = 1, "Nein" = 0),
        b_2___4 = c("Ja" = 1, "Nein" = 0),
        b_3___1 = c("Ja" = 1, "Nein" = 0),
        b_3___2 = c("Ja" = 1, "Nein" = 0),
        b_3___3 = c("Ja" = 1, "Nein" = 0),
        b_3___4 = c("Ja" = 1, "Nein" = 0),
        b_4___1 = c("Ja" = 1, "Nein" = 0),
        b_4___2 = c("Ja" = 1, "Nein" = 0),
        b_4___3 = c("Ja" = 1, "Nein" = 0),
        b_4___4 = c("Ja" = 1, "Nein" = 0),
        c_1___1 = c("Ja" = 1, "Nein" = 0),
        c_1___2 = c("Ja" = 1, "Nein" = 0),
        c_1___3 = c("Ja" = 1, "Nein" = 0),
        c_1___4 = c("Ja" = 1, "Nein" = 0),
        c_1___5 = c("Ja" = 1, "Nein" = 0),
        c_1___6 = c("Ja" = 1, "Nein" = 0),
        c_1___7 = c("Ja" = 1, "Nein" = 0),
        c_1___8 = c("Ja" = 1, "Nein" = 0),
        c_1___9 = c("Ja" = 1, "Nein" = 0),
        c_1___10 = c("Ja" = 1, "Nein" = 0),
        c_2___1 = c("Ja" = 1, "Nein" = 0),
        c_2___2 = c("Ja" = 1, "Nein" = 0),
        c_2___3 = c("Ja" = 1, "Nein" = 0),
        c_2___4 = c("Ja" = 1, "Nein" = 0),
        c_2___5 = c("Ja" = 1, "Nein" = 0),
        c_2___6 = c("Ja" = 1, "Nein" = 0),
        c_2___7 = c("Ja" = 1, "Nein" = 0),
        c_2___8 = c("Ja" = 1, "Nein" = 0),
        c_2___9 = c("Ja" = 1, "Nein" = 0),
        c_2___10 = c("Ja" = 1, "Nein" = 0),
        c_2___11 = c("Ja" = 1, "Nein" = 0),
        c_3___1 = c("Ja" = 1, "Nein" = 0),
        c_3___2 = c("Ja" = 1, "Nein" = 0),
        c_3___3 = c("Ja" = 1, "Nein" = 0),
        c_3___4 = c("Ja" = 1, "Nein" = 0),
        c_3___5 = c("Ja" = 1, "Nein" = 0),
        c_3___6 = c("Ja" = 1, "Nein" = 0),
        c_3___7 = c("Ja" = 1, "Nein" = 0),
        c_3___8 = c("Ja" = 1, "Nein" = 0),
        c_3___9 = c("Ja" = 1, "Nein" = 0),
        c_3___10 = c("Ja" = 1, "Nein" = 0),
        c_6___1 = c("Ja" = 1, "Nein" = 0),
        c_6___2 = c("Ja" = 1, "Nein" = 0),
        c_6___3 = c("Ja" = 1, "Nein" = 0),
        c_6___4 = c("Ja" = 1, "Nein" = 0),
        c_6___5 = c("Ja" = 1, "Nein" = 0),
        c_6___6 = c("Ja" = 1, "Nein" = 0),
        c_7___1 = c("Ja" = 1, "Nein" = 0),
        c_7___2 = c("Ja" = 1, "Nein" = 0),
        c_7___3 = c("Ja" = 1, "Nein" = 0),
        c_7___4 = c("Ja" = 1, "Nein" = 0),
        c_7___5 = c("Ja" = 1, "Nein" = 0),
        c_7___6 = c("Ja" = 1, "Nein" = 0),
        c_8___1 = c("Ja" = 1, "Nein" = 0),
        c_8___2 = c("Ja" = 1, "Nein" = 0),
        c_8___3 = c("Ja" = 1, "Nein" = 0),
        c_8___4 = c("Ja" = 1, "Nein" = 0),
        c_8___5 = c("Ja" = 1, "Nein" = 0),
        c_8___6 = c("Ja" = 1, "Nein" = 0),
        c_8___7 = c("Ja" = 1, "Nein" = 0),
        d_1___1 = c("Ja" = 1, "Nein" = 0),
        d_1___2 = c("Ja" = 1, "Nein" = 0),
        d_1___3 = c("Ja" = 1, "Nein" = 0),
        d_1___4 = c("Ja" = 1, "Nein" = 0),
        d_3___1 = c("Ja" = 1, "Nein" = 0),
        d_3___2 = c("Ja" = 1, "Nein" = 0),
        d_3___3 = c("Ja" = 1, "Nein" = 0),
        d_3___4 = c("Ja" = 1, "Nein" = 0),
        d_3___5 = c("Ja" = 1, "Nein" = 0),
        d_3___6 = c("Ja" = 1, "Nein" = 0),
        d_4___1 = c("Ja" = 1, "Nein" = 0),
        d_4___2 = c("Ja" = 1, "Nein" = 0),
        d_4___3 = c("Ja" = 1, "Nein" = 0),
        d_4___4 = c("Ja" = 1, "Nein" = 0),
        d_4___5 = c("Ja" = 1, "Nein" = 0),
        d_4___6 = c("Ja" = 1, "Nein" = 0)
      ) 
  }    
  
  if(lang == "EN") {
    Sys.setlocale("LC_ALL", "en_US.UTF-8")
    dat0 = dat_in %>%
      # variable labels
      labelled::set_variable_labels(
        type = "Department",
        b_1 = "> Is your authority currently involved in the implementation of measures or activities (e.g., public relations, monitoring, or control) in the area of diseases transmitted by ticks and mosquitoes?",
        b_1_1___1 = "The introduction of measures/activities in the area of diseases transmitted by ticks and mosquitoes is currently being reviewed/planned.",
        b_1_1___2 = "Diseases transmitted by ticks and mosquitoes are not considered part of the responsibilities of your authority.",
        b_1_1___3 = "Diseases transmitted by ticks and mosquitoes are not a high priority for your authority.",
        b_1_1___4 = "The number of cases of diseases transmitted by ticks and mosquitoes is not yet a significant concern to trigger measures in my area.",
        b_1_1___5 = "Lack of financial and/or human resources.",
        b_1_1___6 = "Lack of professionally trained personnel.",
        b_1_1___7 = "Lack of public interest.",
        b_1_1___8 = "Lack of political decision/mandate.",
        b_1_1___9 = "Lack of national guidelines/basics/recommendations to follow.",
        b_1_1___10 = "No information / don't know",
        b_1_1___11 = "Other reasons",
        b_1_2 = "B.1.2. If other reasons in B.1.1: What are they?",
        b_2___1 = "Yes, for tick-borne diseases",
        b_2___2 = "Yes, for mosquito-borne diseases",
        b_2___3 = "No, neither for tick-borne nor mosquito-borne diseases",
        b_2___4 = "No information / don't know",
        b_2_1 = "B.2.1. If Yes in B.2: Can you describe/link this?",
        b_3___1 = "Yes, for tick-borne diseases",
        b_3___2 = "Yes, for mosquito-borne diseases",
        b_3___3 = "No, neither for tick-borne nor mosquito-borne diseases",
        b_3___4 = "No information / don't know",
        b_3_1 = "B.3.1. If Yes: What is the scope of the current staff percentages?",
        b_4___1 = "Yes, for tick-borne diseases",
        b_4___2 = "Yes, for mosquito-borne diseases",
        b_4___3 = "No, neither for tick-borne nor mosquito-borne diseases",
        b_4___4 = "No information / don't know",
        c_1___1 = "Public relations (distribution of educational material about tick-borne diseases to the general public)",
        c_1___2 = "Targeted awareness of professionals (documents on tick-borne diseases)",
        c_1___3 = "Vaccination advice for the population (by health personnel)",
        c_1___4 = "Advice for homeowners on tick management on their property",
        c_1___5 = "Active tick monitoring (collecting ticks in the field for identification, examination, or analysis)",
        c_1___6 = "Passive tick monitoring (acceptance of tick samples submitted by the public, veterinarians, doctors, etc., for identification, examination, or analysis)",
        c_1___7 = "Training and distribution of educational materials",
        c_1___8 = "No information / don't know",
        c_1___9 = "Other: open answer",
        c_1___10 = "My authority does not conduct any activities for tick-borne diseases",
        c_1_1 = "Open answer",
        c_2___1 = "Public relations (distribution of educational material about mosquito-borne diseases to the general public)",
        c_2___2 = "Targeted awareness of professionals (documents on mosquito-borne diseases)",
        c_2___3 = "Active mosquito monitoring (collecting mosquitoes using traps for identification and diagnostics, e.g., Ovitraps)",
        c_2___4 = "Passive mosquito monitoring (acceptance of mosquito submissions and sightings directly from the public or via the Swiss Mosquito Network)",
        c_2___5 = "Verification of mosquito sightings at new locations",
        c_2___6 = "Mosquito control on public land",
        c_2___7 = "Mosquito control on private properties",
        c_2___8 = "Training and distribution of educational materials",
        c_2___9 = "No information / don't know",
        c_2___10 = "Other: open answer",
        c_2___11 = "My authority does not conduct any activities for mosquito-borne diseases",
        c_2_1 = "Open answer",
        c_3___1 = "Correct removal of ticks",
        c_3___2 = "Elimination of mosquito breeding sites",
        c_3___3 = "Vaccinations",
        c_3___4 = "Information on mosquito/tick sprays",
        c_3___5 = "Protection against bites/stings",
        c_3___6 = "Awareness for careful symptom monitoring",
        c_3___7 = "Information on risk areas",
        c_3___8 = "Information on the correct installation of mosquito nets",
        c_3___9 = "No information / don't know",
        c_3___10 = "Other: open answer",
        c_3_1 = "Open answer",
        c_4 = "C.4. How do you disseminate this information (e.g., website, flyers, information events, training)?",
        c_5 = "C.5. Which existing guidelines / support materials / reference documents (e.g., from the federal government, other cantons, national or international organizations) do you / your authority use for the development and implementation of measures?",
        c_6___1 = "Prevention of tick-borne diseases",
        c_6___2 = "Detection of ticks and pathogens in ticks",
        c_6___3 = "Diagnosis of tick-borne diseases",
        c_6___4 = "Management and control of tick-borne diseases",
        c_6___5 = "Therapy/treatment of tick-borne diseases",
        c_6___6 = "Other: open answer",
        c_6_1 = "Open answer",
        c_7___1 = "Prevention of mosquito-borne diseases",
        c_7___2 = "Detection of invasive mosquitoes and pathogens in mosquitoes",
        c_7___3 = "Diagnosis of mosquito-borne diseases",
        c_7___4 = "Management and control of mosquitoes/mosquito-borne diseases",
        c_7___5 = "Therapy/treatment of mosquito-borne diseases",
        c_7___6 = "Other: open answer",
        c_7_1 = "Open answer",
        c_8___1 = "Adulticides (Pyrethroids)",
        c_8___2 = "Non-chemical larvicides",
        c_8___3 = "Biological larvicides",
        c_8___4 = "Elimination of breeding sites",
        c_8___5 = "Sterilization of mosquitoes",
        c_8___6 = "None",
        c_8___7 = "Other: open answer",
        c_8_1 = "Open answer",
        d_1___1 = "Yes, for tick-borne diseases",
        d_1___2 = "Yes, for mosquito-borne diseases",
        d_1___3 = "No, neither for tick-borne nor mosquito-borne diseases",
        d_1___4 = "No information / don't know",
        d_2 = "D.2. In your opinion, where is there a need for support of the cantons by the federal government in the area of diseases transmitted by ticks and mosquitoes?",
        d_3___1 = "Yes, sufficient for tick-borne diseases",
        d_3___2 = "Yes, sufficient for mosquito-borne diseases",
        d_3___3 = "Insufficient for tick-borne diseases",
        d_3___4 = "Insufficient for mosquito-borne diseases",
        d_3___5 = "No, neither for tick-borne nor mosquito-borne diseases",
        d_3___6 = "No information / don't know",
        d_4___1 = "Yes, sufficient for tick-borne diseases",
        d_4___2 = "Yes, sufficient for mosquito-borne diseases",
        d_4___3 = "Insufficient for tick-borne diseases",
        d_4___4 = "Insufficient for mosquito-borne diseases",
        d_4___5 = "No, neither for tick-borne nor mosquito-borne diseases",
        d_4___6 = "No information / don't know"
      ) %>%
      # value labels
      labelled::set_value_labels(
        type= c("Human health"="M","Animal health"="T","Environment"="U"),
        b_1 = c("Yes" = 1, "No" = 2, "No information / don't know" = 3, "Missing" = NA),
        b_1_1___1 = c("Yes" = 1, "No" = 0),
        b_1_1___2 = c("Yes" = 1, "No" = 0),
        b_1_1___3 = c("Yes" = 1, "No" = 0),
        b_1_1___4 = c("Yes" = 1, "No" = 0),
        b_1_1___5 = c("Yes" = 1, "No" = 0),
        b_1_1___6 = c("Yes" = 1, "No" = 0),
        b_1_1___7 = c("Yes" = 1, "No" = 0),
        b_1_1___8 = c("Yes" = 1, "No" = 0),
        b_1_1___9 = c("Yes" = 1, "No" = 0),
        b_1_1___10 = c("Yes" = 1, "No" = 0),
        b_1_1___11 = c("Yes" = 1, "No" = 0),
        b_2___1 = c("Yes" = 1, "No" = 0),
        b_2___2 = c("Yes" = 1, "No" = 0),
        b_2___3 = c("Yes" = 1, "No" = 0),
        b_2___4 = c("Yes" = 1, "No" = 0),
        b_3___1 = c("Yes" = 1, "No" = 0),
        b_3___2 = c("Yes" = 1, "No" = 0),
        b_3___3 = c("Yes" = 1, "No" = 0),
        b_3___4 = c("Yes" = 1, "No" = 0),
        b_4___1 = c("Yes" = 1, "No" = 0),
        b_4___2 = c("Yes" = 1, "No" = 0),
        b_4___3 = c("Yes" = 1, "No" = 0),
        b_4___4 = c("Yes" = 1, "No" = 0),
        c_1___1 = c("Yes" = 1, "No" = 0),
        c_1___2 = c("Yes" = 1, "No" = 0),
        c_1___3 = c("Yes" = 1, "No" = 0),
        c_1___4 = c("Yes" = 1, "No" = 0),
        c_1___5 = c("Yes" = 1, "No" = 0),
        c_1___6 = c("Yes" = 1, "No" = 0),
        c_1___7 = c("Yes" = 1, "No" = 0),
        c_1___8 = c("Yes" = 1, "No" = 0),
        c_1___9 = c("Yes" = 1, "No" = 0),
        c_1___10 = c("Yes" = 1, "No" = 0),
        c_2___1 = c("Yes" = 1, "No" = 0),
        c_2___2 = c("Yes" = 1, "No" = 0),
        c_2___3 = c("Yes" = 1, "No" = 0),
        c_2___4 = c("Yes" = 1, "No" = 0),
        c_2___5 = c("Yes" = 1, "No" = 0),
        c_2___6 = c("Yes" = 1, "No" = 0),
        c_2___7 = c("Yes" = 1, "No" = 0),
        c_2___8 = c("Yes" = 1, "No" = 0),
        c_2___9 = c("Yes" = 1, "No" = 0),
        c_2___10 = c("Yes" = 1, "No" = 0),
        c_2___11 = c("Yes" = 1, "No" = 0),
        c_3___1 = c("Yes" = 1, "No" = 0),
        c_3___2 = c("Yes" = 1, "No" = 0),
        c_3___3 = c("Yes" = 1, "No" = 0),
        c_3___4 = c("Yes" = 1, "No" = 0),
        c_3___5 = c("Yes" = 1, "No" = 0),
        c_3___6 = c("Yes" = 1, "No" = 0),
        c_3___7 = c("Yes" = 1, "No" = 0),
        c_3___8 = c("Yes" = 1, "No" = 0),
        c_3___9 = c("Yes" = 1, "No" = 0),
        c_3___10 = c("Yes" = 1, "No" = 0),
        c_6___1 = c("Yes" = 1, "No" = 0),
        c_6___2 = c("Yes" = 1, "No" = 0),
        c_6___3 = c("Yes" = 1, "No" = 0),
        c_6___4 = c("Yes" = 1, "No" = 0),
        c_6___5 = c("Yes" = 1, "No" = 0),
        c_6___6 = c("Yes" = 1, "No" = 0),
        c_7___1 = c("Yes" = 1, "No" = 0),
        c_7___2 = c("Yes" = 1, "No" = 0),
        c_7___3 = c("Yes" = 1, "No" = 0),
        c_7___4 = c("Yes" = 1, "No" = 0),
        c_7___5 = c("Yes" = 1, "No" = 0),
        c_7___6 = c("Yes" = 1, "No" = 0),
        c_8___1 = c("Yes" = 1, "No" = 0),
        c_8___2 = c("Yes" = 1, "No" = 0),
        c_8___3 = c("Yes" = 1, "No" = 0),
        c_8___4 = c("Yes" = 1, "No" = 0),
        c_8___5 = c("Yes" = 1, "No" = 0),
        c_8___6 = c("Yes" = 1, "No" = 0),
        c_8___7 = c("Yes" = 1, "No" = 0),
        d_1___1 = c("Yes" = 1, "No" = 0),
        d_1___2 = c("Yes" = 1, "No" = 0),
        d_1___3 = c("Yes" = 1, "No" = 0),
        d_1___4 = c("Yes" = 1, "No" = 0),
        d_3___1 = c("Yes" = 1, "No" = 0),
        d_3___2 = c("Yes" = 1, "No" = 0),
        d_3___3 = c("Yes" = 1, "No" = 0),
        d_3___4 = c("Yes" = 1, "No" = 0),
        d_3___5 = c("Yes" = 1, "No" = 0),
        d_3___6 = c("Yes" = 1, "No" = 0),
        d_4___1 = c("Yes" = 1, "No" = 0),
        d_4___2 = c("Yes" = 1, "No" = 0),
        d_4___3 = c("Yes" = 1, "No" = 0),
        d_4___4 = c("Yes" = 1, "No" = 0),
        d_4___5 = c("Yes" = 1, "No" = 0),
        d_4___6 = c("Yes" = 1, "No" = 0)
      )
  }
  
  # common to all 3 languages
  dat1 = dat0 %>%
    # missing
    dplyr::mutate(
      b_1 = dplyr::na_if(b_1, 3),
      b_2___1 = dplyr::na_if(b_2___1, 4),
      b_2___2 = dplyr::na_if(b_2___2, 4),
      b_2___3 = dplyr::na_if(b_2___3, 4),
      b_2___4 = dplyr::na_if(b_2___4, 4),
      b_3___1 = dplyr::na_if(b_3___1, 4),
      b_3___2 = dplyr::na_if(b_3___2, 4),
      b_3___3 = dplyr::na_if(b_3___3, 4),
      b_3___4 = dplyr::na_if(b_3___4, 4),
      b_4___1 = dplyr::na_if(b_4___1, 4),
      b_4___2 = dplyr::na_if(b_4___2, 4),
      b_4___3 = dplyr::na_if(b_4___3, 4),
      b_4___4 = dplyr::na_if(b_4___4, 4),
      c_1___1 = dplyr::na_if(c_1___1, 8),
      c_1___2 = dplyr::na_if(c_1___2, 8),
      c_1___3 = dplyr::na_if(c_1___3, 8),
      c_1___4 = dplyr::na_if(c_1___4, 8),
      c_1___5 = dplyr::na_if(c_1___5, 8),
      c_1___6 = dplyr::na_if(c_1___6, 8),
      c_1___7 = dplyr::na_if(c_1___7, 8),
      c_1___8 = dplyr::na_if(c_1___8, 8),
      c_1___9 = dplyr::na_if(c_1___9, 8),
      c_1___10 = dplyr::na_if(c_1___10, 8),
      c_2___1 = dplyr::na_if(c_2___1, 9),
      c_2___2 = dplyr::na_if(c_2___2, 9),
      c_2___3 = dplyr::na_if(c_2___3, 9),
      c_2___4 = dplyr::na_if(c_2___4, 9),
      c_2___5 = dplyr::na_if(c_2___5, 9),
      c_2___6 = dplyr::na_if(c_2___6, 9),
      c_2___7 = dplyr::na_if(c_2___7, 9),
      c_2___8 = dplyr::na_if(c_2___8, 9),
      c_2___9 = dplyr::na_if(c_2___9, 9),
      c_2___10 = dplyr::na_if(c_2___10, 9),
      c_2___11 = dplyr::na_if(c_2___11, 9),
      c_3___1 = dplyr::na_if(c_3___1, 9),
      c_3___2 = dplyr::na_if(c_3___2, 9),
      c_3___3 = dplyr::na_if(c_3___3, 9),
      c_3___4 = dplyr::na_if(c_3___4, 9),
      c_3___5 = dplyr::na_if(c_3___5, 9),
      c_3___6 = dplyr::na_if(c_3___6, 9),
      c_3___7 = dplyr::na_if(c_3___7, 9),
      c_3___8 = dplyr::na_if(c_3___8, 9),
      c_3___9 = dplyr::na_if(c_3___9, 9),
      c_3___10 = dplyr::na_if(c_3___10, 9),
      c_6___1 = dplyr::na_if(c_6___1, 6),
      c_6___2 = dplyr::na_if(c_6___2, 6),
      c_6___3 = dplyr::na_if(c_6___3, 6),
      c_6___4 = dplyr::na_if(c_6___4, 6),
      c_6___5 = dplyr::na_if(c_6___5, 6),
      c_6___6 = dplyr::na_if(c_6___6, 6),
      c_7___1 = dplyr::na_if(c_7___1, 6),
      c_7___2 = dplyr::na_if(c_7___2, 6),
      c_7___3 = dplyr::na_if(c_7___3, 6),
      c_7___4 = dplyr::na_if(c_7___4, 6),
      c_7___5 = dplyr::na_if(c_7___5, 6),
      c_7___6 = dplyr::na_if(c_7___6, 6),
      c_8___1 = dplyr::na_if(c_8___1, 7),
      c_8___2 = dplyr::na_if(c_8___2, 7),
      c_8___3 = dplyr::na_if(c_8___3, 7),
      c_8___4 = dplyr::na_if(c_8___4, 7),
      c_8___5 = dplyr::na_if(c_8___5, 7),
      c_8___6 = dplyr::na_if(c_8___6, 7),
      c_8___7 = dplyr::na_if(c_8___7, 7),
      d_1___1 = dplyr::na_if(d_1___1, 4),
      d_1___2 = dplyr::na_if(d_1___2, 4),
      d_1___3 = dplyr::na_if(d_1___3, 4),
      d_1___4 = dplyr::na_if(d_1___4, 4),
      d_3___1 = dplyr::na_if(d_3___1, 6),
      d_3___2 = dplyr::na_if(d_3___2, 6),
      d_3___3 = dplyr::na_if(d_3___3, 6),
      d_3___4 = dplyr::na_if(d_3___4, 6),
      d_3___5 = dplyr::na_if(d_3___5, 6),
      d_3___6 = dplyr::na_if(d_3___6, 6),
      d_4___1 = dplyr::na_if(d_4___1, 6),
      d_4___2 = dplyr::na_if(d_4___2, 6),
      d_4___3 = dplyr::na_if(d_4___3, 6),
      d_4___4 = dplyr::na_if(d_4___4, 6),
      d_4___5 = dplyr::na_if(d_4___5, 6),
      d_4___6 = dplyr::na_if(d_4___6, 6)
    ) %>%
    # format
    dplyr::mutate(
      type = labelled::to_factor(type),
      b_1 = labelled::to_factor(b_1),
      b_1_1___1 = labelled::to_factor(b_1_1___1),
      b_1_1___2 = labelled::to_factor(b_1_1___2),
      b_1_1___3 = labelled::to_factor(b_1_1___3),
      b_1_1___4 = labelled::to_factor(b_1_1___4),
      b_1_1___5 = labelled::to_factor(b_1_1___5),
      b_1_1___6 = labelled::to_factor(b_1_1___6),
      b_1_1___7 = labelled::to_factor(b_1_1___7),
      b_1_1___8 = labelled::to_factor(b_1_1___8),
      b_1_1___9 = labelled::to_factor(b_1_1___9),
      b_1_1___10 = labelled::to_factor(b_1_1___10),
      b_1_1___11 = labelled::to_factor(b_1_1___11),
      b_2___1 = labelled::to_factor(b_2___1),
      b_2___2 = labelled::to_factor(b_2___2),
      b_2___3 = labelled::to_factor(b_2___3),
      b_2___4 = labelled::to_factor(b_2___4),
      b_3___1 = labelled::to_factor(b_3___1),
      b_3___2 = labelled::to_factor(b_3___2),
      b_3___3 = labelled::to_factor(b_3___3),
      b_3___4 = labelled::to_factor(b_3___4),
      b_4___1 = labelled::to_factor(b_4___1),
      b_4___2 = labelled::to_factor(b_4___2),
      b_4___3 = labelled::to_factor(b_4___3),
      b_4___4 = labelled::to_factor(b_4___4),
      c_1___1 = labelled::to_factor(c_1___1),
      c_1___2 = labelled::to_factor(c_1___2),
      c_1___3 = labelled::to_factor(c_1___3),
      c_1___4 = labelled::to_factor(c_1___4),
      c_1___5 = labelled::to_factor(c_1___5),
      c_1___6 = labelled::to_factor(c_1___6),
      c_1___7 = labelled::to_factor(c_1___7),
      c_1___8 = labelled::to_factor(c_1___8),
      c_1___9 = labelled::to_factor(c_1___9),
      c_1___10 = labelled::to_factor(c_1___10),
      c_2___1 = labelled::to_factor(c_2___1),
      c_2___2 = labelled::to_factor(c_2___2),
      c_2___3 = labelled::to_factor(c_2___3),
      c_2___4 = labelled::to_factor(c_2___4),
      c_2___5 = labelled::to_factor(c_2___5),
      c_2___6 = labelled::to_factor(c_2___6),
      c_2___7 = labelled::to_factor(c_2___7),
      c_2___8 = labelled::to_factor(c_2___8),
      c_2___9 = labelled::to_factor(c_2___9),
      c_2___10 = labelled::to_factor(c_2___10),
      c_2___11 = labelled::to_factor(c_2___11),
      c_3___1 = labelled::to_factor(c_3___1),
      c_3___2 = labelled::to_factor(c_3___2),
      c_3___3 = labelled::to_factor(c_3___3),
      c_3___4 = labelled::to_factor(c_3___4),
      c_3___5 = labelled::to_factor(c_3___5),
      c_3___6 = labelled::to_factor(c_3___6),
      c_3___7 = labelled::to_factor(c_3___7),
      c_3___8 = labelled::to_factor(c_3___8),
      c_3___9 = labelled::to_factor(c_3___9),
      c_3___10 = labelled::to_factor(c_3___10),
      c_6___1 = labelled::to_factor(c_6___1),
      c_6___2 = labelled::to_factor(c_6___2),
      c_6___3 = labelled::to_factor(c_6___3),
      c_6___4 = labelled::to_factor(c_6___4),
      c_6___5 = labelled::to_factor(c_6___5),
      c_6___6 = labelled::to_factor(c_6___6),
      c_7___1 = labelled::to_factor(c_7___1),
      c_7___2 = labelled::to_factor(c_7___2),
      c_7___3 = labelled::to_factor(c_7___3),
      c_7___4 = labelled::to_factor(c_7___4),
      c_7___5 = labelled::to_factor(c_7___5),
      c_7___6 = labelled::to_factor(c_7___6),
      c_8___1 = labelled::to_factor(c_8___1),
      c_8___2 = labelled::to_factor(c_8___2),
      c_8___3 = labelled::to_factor(c_8___3),
      c_8___4 = labelled::to_factor(c_8___4),
      c_8___5 = labelled::to_factor(c_8___5),
      c_8___6 = labelled::to_factor(c_8___6),
      c_8___7 = labelled::to_factor(c_8___7),
      d_1___1 = labelled::to_factor(d_1___1),
      d_1___2 = labelled::to_factor(d_1___2),
      d_1___3 = labelled::to_factor(d_1___3),
      d_1___4 = labelled::to_factor(d_1___4),
      d_3___1 = labelled::to_factor(d_3___1),
      d_3___2 = labelled::to_factor(d_3___2),
      d_3___3 = labelled::to_factor(d_3___3),
      d_3___4 = labelled::to_factor(d_3___4),
      d_3___5 = labelled::to_factor(d_3___5),
      d_3___6 = labelled::to_factor(d_3___6),
      d_4___1 = labelled::to_factor(d_4___1),
      d_4___2 = labelled::to_factor(d_4___2),
      d_4___3 = labelled::to_factor(d_4___3),
      d_4___4 = labelled::to_factor(d_4___4),
      d_4___5 = labelled::to_factor(d_4___5),
      d_4___6 = labelled::to_factor(d_4___6)
    )
  
  if(FALSE) {
    dat1 %>% 
      dplyr::select(-(1:4)) %>%
      gtsummary::tbl_summary()
  }
  
  # Return
  dat_out = dat1
  return(dat_out)
}


